### ISSUE TITLE
Create API endpoint for hash tag filtering

### ISSUE THREAD

**Issue by xavez** [oSoc17/datascouts#100] opened 2017-07-23 20:25 UTC
We need to be able to filter on hash tags in the front-end.

Use case: I want to be able to see all posts with #bitcoin across the YouTube, twitter and Vimeo accounts I am following.

**Comment by mrvdries** [comment] 2017-07-26 15:36
Closing, duplicate of #129

**Closed as completed by mrvdries** 2017-07-26 15:36 UTC
Labels: frontend
