### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by mrvdries** [oSoc17/datascouts#83] opened 2017-07-17 11:06 UTC
# Feature #85 
The front-end code should be refactored so that Max isn't the only one in the world who can read it without getting a major headache. 

- [x] Webpack-simple boilerplate
- [x] Vue-ressource or axios ( to Handle the XHRRequest )
- [ ] Design the structure (The communication btwn component)

## Components :
- [x] Main
- [x] Entity sidebar
  - [x] Entities list
  - [x] Add entity
- [x] Handle sidebar
  - [x] Edit entity
  - [x] Handles list
- [x] Add handle
- [x] Waterfall display

**Comment by xavez** [comment] 2017-07-23 19:49
Closing this, the issue is too big. We need to make specific small tasks.

**Closed as completed by xavez** 2017-07-23 19:49 UTC
Labels: frontend
